/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

import static org.example.util.UserServiceUtil.hashPassword;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
            System.out.println(new App().getGreeting());
            Scanner sc=new Scanner(System.in);
            int option=0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        }
        catch (IOException e)
        {
            System.out.println("something went wrong");
            return;
        }

        while (option != 4) {
            System.out.println("1. Login");
            System.out.println("2. Sign up");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Exit");
            option = sc.nextInt();
            if (option == 1) {
                userBookingService.loginUser();
            } else if (option == 2) {
                String nameToSignup = sc.next();
                String passwordToSignup = sc.next();
                User user = new User(nameToSignup, passwordToSignup, hashPassword(passwordToSignup),new ArrayList<>(), UUID.randomUUID().toString());
                userBookingService.signUp(nameToSignup, passwordToSignup);
            } else if (option == 3) {
                userBookingService.fetchBooking();
            }
        }
    }
}
